#!/usr/bin/env python3
"""
build_standalone.py — bake the playtest into ONE double-clickable HTML file.

`prototype/playtest_build.html` fetches the data spine from `data/`, which means
it needs a local server (fetch is blocked on file://). This script inlines
roster.json + effects.json into a single self-contained file you can email,
copy to a USB stick, or open by double-clicking on any machine with a browser.

    python3 tools/build_standalone.py

Output: prototype/playtest_standalone.html  (GENERATED — do not hand-edit)

The source of truth stays `prototype/playtest_build.html` + `data/*.json`.
Re-run this after changing either. Runs from anywhere.
"""
import json, pathlib, sys, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = ROOT / "prototype" / "playtest_build.html"
OUT  = ROOT / "prototype" / "playtest_standalone.html"
DATA = ROOT / "data"

def main():
    for f in (SRC, DATA/"roster.json", DATA/"effects.json"):
        if not f.exists():
            sys.exit(f"missing: {f}")

    html    = SRC.read_text()
    roster  = json.loads((DATA/"roster.json").read_text())
    effects = json.loads((DATA/"effects.json").read_text())

    # Compact JSON, and escape "</" so a stray sequence can't close our <script>.
    blob = json.dumps({"roster": roster, "effects": effects},
                      separators=(",", ":")).replace("</", "<\\/")

    stamp = datetime.date.today().isoformat()
    banner = (f"<!-- GENERATED by tools/build_standalone.py on {stamp}. Do not edit by hand.\n"
              f"     Source: prototype/playtest_build.html + data/*.json -->\n")
    inject = f'<script>window.__TRUESERVE_DATA={blob};</script>\n'

    anchor = "<script>\n/* ====="
    if anchor not in html:
        sys.exit("could not find the main <script> block to inject before")
    out = banner + html.replace(anchor, inject + anchor, 1)

    OUT.write_text(out)
    mb = len(out.encode()) / 1024 / 1024
    print(f"wrote {OUT.relative_to(ROOT)}  ({mb:.2f} MB, "
          f"{len(roster['units'])} units, {len(effects['effects'])} effects)")
    print("Double-click it, or copy it anywhere — no server, no other files needed.")

if __name__ == "__main__":
    main()
